SELECT count(distinct "PRICE")  as total_houses_sold FROM "MARS"."HOUSING";


											--LOOKING FOR DUPLICATES
											
-- HOW MANY KINDS OF HOUSES HAVE BEEN SOLD

SELECT 
  "TITLE", 
  COUNT(*) AS House_types 
FROM "MARS"."HOUSING" 
GROUP BY "TITLE" 
ORDER BY "TITLE";

SELECT "TITLE", COUNT(DISTINCT 'BLOCK OF FLATS') 
  AS House_types 
FROM "MARS"."HOUSING"
GROUP BY "TITLE" 
ORDER BY "TITLE";

SELECT 
  "TITLE",
  TO_CHAR("PRICE", 'FM₦999,999,999,999.00') AS formatted_price
FROM "MARS"."HOUSING"
WHERE "TITLE" ILIKE 'BLOCK OF FLATS';

ALTER TABLE "MARS"."HOUSING"
ALTER COLUMN "PRICE" TYPE TEXT
USING TO_CHAR("PRICE", 'FM₦999,999,999,999.00');

SELECT * FROM "MARS"."HOUSING";

SELECT * 
FROM "MARS"."HOUSING",TO_CHAR("PRICE", 'FM₦999,999,999,999.00') AS formatted_price
WHERE "TITLE" ILIKE 'BLOCK OF FLATS';



  --CHANGE THE PRICE COLUMN INTO CURRENCY FORMAT

 SELECT 
  "TITLE",
  TO_CHAR("PRICE", 'FM₦999,999,999,999.00') AS formatted_price
FROM "MARS"."HOUSING";

											

-- THIS WILL SHOW YOU ALL THE DETACHED 

SELECT * 
FROM "MARS"."HOUSING"
WHERE "TITLE" ILIKE '%Detached DUPLEX%';

-- THIS WILL SHOW YOU ALL THE DETACHED HOUSES FROM LAGOS
SELECT * FROM "MARS"."HOUSING" 
WHERE "TITLE" ILIKE '%Detached DUPLEX%'
AND "STATE" ILIKE '%lagos%';

--SHOW ALL HOUSES FRON OYO AND EDO

SELECT *
FROM "MARS"."HOUSING"
WHERE "STATE" ILIKE 'EDO' 
   OR "STATE" ILIKE 'OYO'
   LIMIT 50;

SELECT COUNT(*) AS total_duplex_houses
FROM "MARS"."HOUSING"
WHERE "TITLE" ILIKE '%Detached DUPLEX%';

--THE TOTAL OF A PARTICULAR HOUSE IN A PLACE 
SELECT *
FROM "MARS"."HOUSING"
WHERE "TITLE" ILIKE 'Detached DUPLEX'
AND "STATE" ILIKE 'OYO'
OR "STATE" ILIKE 'ABUJA'
   LIMIT 50;

--I WANT TO COUNT ALL THE DETACHED DUPLEX FROM LAGOS 

SELECT COUNT(*) AS total_duplex_houses
FROM "MARS"."HOUSING"
WHERE 
  "TITLE" ILIKE '%detached%duplex%' AND 
  "STATE" ILIKE 'abuja'; 

  -- I WaNT TO FIND OUT THE OTHER STATE WHERE DETACHED HOUSES ARE SOLD APART FROM ABUJA AND LAGOS

  SELECT *
FROM "MARS"."HOUSING"
WHERE 
  "STATE" NOT ILIKE '%Lagos%' 
  AND "STATE" NOT ILIKE '%Abuja%';

  -- COUNT HOW MANY HOUSES WAS SOLD THAT WHERE NOT FROM LAGOS OR ABUJA

  SELECT COUNT(*) AS total_duplex_houses
FROM "MARS"."HOUSING"
WHERE 
  "STATE" NOT ILIKE '%Lagos%' 
  AND "STATE" NOT ILIKE '%Abuja%';


  --CHANGE THE PRICE COLUMN INTO CURRENCY FORMAT

 SELECT 
  "TITLE",
  TO_CHAR("PRICE", 'FM₦999,999,999,999.00') AS formatted_price
FROM "MARS"."HOUSING";


--FINDING MISSING VALUES 

SELECT *
FROM "MARS"."HOUSING"
WHERE "PARKING_SPACE" IS NULL;

-- COMPARING TABLES TO KNOW ROWS THAT DOES NOT EXIST IN ANOTHER

SELECT "BATHROOM","BEDROOM"
FROM "MARS"."HOUSING"
EXCEPT
SELECT "BATHROOM","BEDROOM"
FROM "MARS"."HOUSING_1";

--Find rows where a column does not contain expected values:
SELECT *
FROM "MARS"."HOUSING"
WHERE "TITLE" NOT IN ( 'Detached', 'Semi-Detached','Block of Flats');


--Ensure all required columns have data (non-NULL and non-empty):
SELECT *
FROM "MARS"."HOUSING"
WHERE 
  "TITLE" IS NULL 
  OR "PRICE" IS NULL 
  OR "STATE" IS NULL
  OR "TOWN" IS NULL
  OR "BATHROOM" IS NULL
  OR "BEDROOM" IS NULL
  OR "TOILET" IS NULL;

--Find houses in one table with no matching entries in another:

SELECT *
FROM "MARS"."HOUSING" h
WHERE NOT EXISTS (
  SELECT 1
  FROM "MARS"."HOUSING_1" s
  WHERE h."TITLE" = s."TITLE"
);


--Fix inconsistencies in text, dates, or numeric values.

UPDATE "MARS"."HOUSING"
SET  
  "STATE" = TRIM(INITCAP("STATE"));


  UPDATE "MARS"."HOUSING"
SET "TOWN" = NULL
WHERE TRIM("TOWN") = '';







  
